title:              Max's homepage
email:              slotamax15@gmail.com
description:        A collection of my projects
author:             Max SÅ‚ota
baseurl:            ""
url:                "https://worthy11.github.io"

# Social Profiles
github_username:    worthy11
linkedin_username:  max-s%C5%82ota-3833b3259/

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
